
// Code generated by tools/gen_shims. DO NOT EDIT.

package execute

import "github.com/microsoft/typescript-go/internal/execute"
import "github.com/microsoft/typescript-go/internal/execute/tsc"
import _ "unsafe"

//go:linkname CommandLine github.com/microsoft/typescript-go/internal/execute.CommandLine
func CommandLine(sys tsc.System, commandLineArgs []string, testing tsc.CommandLineTesting) tsc.CommandLineResult
type Watcher = execute.Watcher
